#coding=utf-8


model_app_type_dict = {}

model_app_type_dict["Kissht"]    = "jingpin"
model_app_type_dict["ePaylater"] = "jingpin"
model_app_type_dict["LazyPay"]   = "jingpin"
model_app_type_dict["ZestMoney"] = "jingpin"
model_app_type_dict["Simpl"] 	 = "jingpin"

model_app_type_dict["SBI Card"] 	    = "bank"
model_app_type_dict["iMobile"] 	            = "bank"
model_app_type_dict["PNB"] 		    = "bank"
model_app_type_dict["BOI Mobile"] 	    = "bank"
model_app_type_dict["M-Connect"] 	    = "bank"
model_app_type_dict["HDFC Bank"] 	    = "bank"
model_app_type_dict["Canara eInfobook"]     = "bank"
model_app_type_dict["RBI"] 		    = "bank"
model_app_type_dict["U-Mobile"] 	    = "bank"
model_app_type_dict["IOBMobile"] 	    = "bank"
model_app_type_dict["Axis Mobile"] 	    = "bank"
model_app_type_dict["Bajaj Finserv"] 	    = "bank"
model_app_type_dict["Mahindra Finance"]     = "bank"
model_app_type_dict["IDBI Bank"] 	    = "bank"
model_app_type_dict["emPower"] 	            = "bank"



model_app_type_dict["PaySense"]             = "loan"
model_app_type_dict["EarlySalary"]          = "loan"
model_app_type_dict["CASHe"]                = "loan"
model_app_type_dict["MoneyTap"]             = "loan"
model_app_type_dict["KreditBee"]            = "loan"
model_app_type_dict["Indiabulls Dhani"]     = "loan"
model_app_type_dict["StashFin"]             = "loan"
model_app_type_dict["SmartCoin"]            = "loan"
model_app_type_dict["Credy"]                = "loan"
model_app_type_dict["Dhani"]                = "loan"
model_app_type_dict["Early Salary"]         = "loan"
model_app_type_dict["NIRA"]                 = "loan"
model_app_type_dict["Money Tap"]            = "loan"
model_app_type_dict["FlexSalary"]           = "loan"
model_app_type_dict["MoneyView"]            = "loan"
model_app_type_dict["PayMe India"]          = "loan"
model_app_type_dict["Kredit Bee"]           = "loan"
model_app_type_dict["Smart Coin"]           = "loan"
model_app_type_dict["Rupeelend"]            = "loan"
model_app_type_dict["mPokket"]              = "loan"
model_app_type_dict["Home Credit"]          = "loan"
model_app_type_dict["Anytime Loan"]         = "loan"
model_app_type_dict["ATL"]                  = "loan"
model_app_type_dict["Capital First"]        = "loan"
model_app_type_dict["Opta Credit"]          = "loan"
model_app_type_dict["Loan Tap"]             = "loan"
model_app_type_dict["Olly Credit"]          = "loan"
model_app_type_dict["Personal Capital"]     = "loan"
model_app_type_dict["Clarity Money"]        = "loan"
model_app_type_dict["Prism"]                = "loan"
model_app_type_dict["Mobills"]              = "loan"
model_app_type_dict["CashBean"]             = "loan"
model_app_type_dict["Mi Credit"]            = "loan"
model_app_type_dict["Avail"]                = "loan"
model_app_type_dict["WifiCash"]             = "loan"
model_app_type_dict["RupeeMax"]             = "loan"
model_app_type_dict["Cash Bowl"]            = "loan"
model_app_type_dict["Erupee"]               = "loan"
model_app_type_dict["CashIn"]               = "loan"
model_app_type_dict["Kreditzy"]             = "loan"
model_app_type_dict["iCredit"]              = "loan"
model_app_type_dict["MoneyClick"]           = "loan"
model_app_type_dict["Bajaj Finserv"]        = "loan"
